spring.application.name=microservicegateway
server.port=8888

#eureka config
eureka.client.service-url.defaultZone=http://localhost:9999/eureka

#route microservicepet
spring.cloud.gateway.server.webflux.routes[0].id=microservicepet
spring.cloud.gateway.server.webflux.routes[0].uri=lb://microservicepet
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/pet/**

#route microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].id=microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].uri=lb://microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/adopter/**

#route microserviceadoption
spring.cloud.gateway.server.webflux.routes[2].id=microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].uri=lb://microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/adoption/**
