spring.application.name=microserviceadoptionrequest

server.port=9093

#hibernate config
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#datasource config
spring.datasource.url=jdbc:mysql://localhost:3306/microserviceadoptionrequest
spring.datasource.username=root
spring.datasource.password=abc123

#eureka configuration
eureka.client.service-url.defaultZone=http://localhost:9999/eureka
